名称：生锈：生锈

在……之上:
推:
分支机构：[“主”]: [ "主" ]
pull_request:
分支机构：[“主”]: [ "主" ]

env:
cargo_TERM_COLOR：始终: 总是

工作:
建立:

run-on:ubuntu-latest: Ubuntu-最新

步骤:
-使用：操作/结帐@v4uses: 操作/结帐@v4
-名称：内部版本名: 建立
运行：货物建造--详细: 货物造型--------------------------------------------------------
-名称：运行测试name: 运行测试
运行：货物测试--详细: 货物试验--详细
